version: '3.8'
services:
  db:
    image: postgres:14
    container_name: nest_app_postgres
    ports:
      - 5434:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/morimoripon
      - JWT_SECRET=3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R
      - POSTGRES_DB=morimoripon
      - POSTGRES_PASSWORD=password
    networks:
      - default_network
  api:
    container_name: nest_app_nestjs
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@172.17.0.1:5434/morimoripon?schema=public
      - JWT_SECRET=3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R
      - WEB_URL=http://172.17.0.1:3000
    networks:
      - default_network
  frontend:
    container_name: nest_app_nextjs
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - default_network
volumes:
  db-store:
networks:
  default_network:
